<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="chassis_length" value="0.8"/>
    <xacro:property name="chassis_width" value="0.8"/>
    <xacro:property name="chassis_height" value="0.3"/>
    <xacro:property name="chassis_mass" value="0.4"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_thickness" value="0.06"/>
    <xacro:property name="wheel_mass" value="0.5"/>
    <xacro:property name="wheel_offset_x" value="${chassis_length/2}"/>
    <xacro:property name="wheel_offset_y" value="${chassis_width/2 + wheel_thickness/2}"/>
    <!-- <xacro:property name="wheel_offset_z" value="0.01"/> -->
    <xacro:property name="caster_wheel_radius" value="${wheel_radius}"/>
    <xacro:property name="caster_wheel_mass" value="0.05"/>
    <xacro:property name="caster_wheel_offset_x" value="${wheel_offset_x}"/>
    <!-- <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/> -->

</robot>